sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages: # recommended versions for rust-bindgen
      - r-base-dev
      - llvm-3.9-dev
      - libclang-3.9-dev

env: # specify the clang path for rust-bindgen
  - LIBCLANG_PATH=/usr/lib/llvm-3.9/lib

script:
  - cargo build
  - cargo test
