/* automatically generated by rust-bindgen 0.69.4 */

/* libR-sys version: 0.7.0 */
/* bindgen clang version: clang version 16.0.6 */
/* r version: 4.5.0-devel */

pub const HAVE_F77_UNDERSCORE: u32 = 1;
pub const IEEE_754: u32 = 1;
pub const SUPPORT_UTF8: u32 = 1;
pub const SUPPORT_MBCS: u32 = 1;
pub const ENABLE_NLS: u32 = 1;
pub const PR18534fixed: u32 = 1;
pub const SIZEOF_SIZE_T: u32 = 8;
pub const HAVE_UINTPTR_T: u32 = 1;
#[doc = "R_xlen_t is defined as int on 32-bit platforms, and\n that confuses Rust. Keeping it always as ptrdiff_t works\n fine even on 32-bit.\n <div rustbindgen replaces=\"R_xlen_t\"></div>"]
pub type R_xlen_t = isize;
extern "C" {
    #[doc = "not of themselves API"]
    pub fn R_chk_calloc(arg1: usize, arg2: usize) -> *mut ::std::os::raw::c_void;
    pub fn R_chk_realloc(
        arg1: *mut ::std::os::raw::c_void,
        arg2: usize,
    ) -> *mut ::std::os::raw::c_void;
    pub fn R_chk_free(arg1: *mut ::std::os::raw::c_void);
    pub fn dpbfa_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut ::std::os::raw::c_int,
    );
    pub fn dpbsl_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut f64,
    );
    pub fn dpoco_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut f64,
        arg5: *mut f64,
        arg6: *mut ::std::os::raw::c_int,
    );
    pub fn dpodi_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut f64,
        arg5: *mut ::std::os::raw::c_int,
    );
    pub fn dpofa_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
    );
    pub fn dposl_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut f64,
    );
    pub fn dqrdc_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut f64,
        arg6: *mut ::std::os::raw::c_int,
        arg7: *mut f64,
        arg8: *mut ::std::os::raw::c_int,
    );
    pub fn dqrsl_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut f64,
        arg6: *mut f64,
        arg7: *mut f64,
        arg8: *mut f64,
        arg9: *mut f64,
        arg10: *mut f64,
        arg11: *mut f64,
        arg12: *mut ::std::os::raw::c_int,
        arg13: *mut ::std::os::raw::c_int,
    );
    pub fn dsvdc_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut f64,
        arg6: *mut f64,
        arg7: *mut f64,
        arg8: *mut ::std::os::raw::c_int,
        arg9: *mut f64,
        arg10: *mut ::std::os::raw::c_int,
        arg11: *mut f64,
        arg12: *mut ::std::os::raw::c_int,
        arg13: *mut ::std::os::raw::c_int,
    );
    pub fn dtrco_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut f64,
        arg5: *mut f64,
        arg6: *mut ::std::os::raw::c_int,
    );
    pub fn dtrsl_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut f64,
        arg5: *mut ::std::os::raw::c_int,
        arg6: *mut ::std::os::raw::c_int,
    );
    pub fn dchdc_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut f64,
        arg5: *mut ::std::os::raw::c_int,
        arg6: *mut ::std::os::raw::c_int,
        arg7: *mut ::std::os::raw::c_int,
    );
    pub fn dchdd_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut f64,
        arg5: *mut f64,
        arg6: *mut ::std::os::raw::c_int,
        arg7: *mut ::std::os::raw::c_int,
        arg8: *mut f64,
        arg9: *mut f64,
        arg10: *mut f64,
        arg11: *mut f64,
        arg12: *mut ::std::os::raw::c_int,
    );
    pub fn dchex_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut ::std::os::raw::c_int,
        arg6: *mut f64,
        arg7: *mut ::std::os::raw::c_int,
        arg8: *mut ::std::os::raw::c_int,
        arg9: *mut f64,
        arg10: *mut f64,
        arg11: *mut ::std::os::raw::c_int,
    );
    pub fn dchud_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut f64,
        arg5: *mut f64,
        arg6: *mut ::std::os::raw::c_int,
        arg7: *mut ::std::os::raw::c_int,
        arg8: *mut f64,
        arg9: *mut f64,
        arg10: *mut f64,
        arg11: *mut f64,
    );
    pub fn dgbco_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut ::std::os::raw::c_int,
        arg6: *mut ::std::os::raw::c_int,
        arg7: *mut f64,
        arg8: *mut f64,
    );
    pub fn dgbdi_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut ::std::os::raw::c_int,
        arg6: *mut ::std::os::raw::c_int,
        arg7: *mut f64,
    );
    pub fn dgbfa_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut ::std::os::raw::c_int,
        arg6: *mut ::std::os::raw::c_int,
        arg7: *mut ::std::os::raw::c_int,
    );
    pub fn dgbsl_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut ::std::os::raw::c_int,
        arg6: *mut ::std::os::raw::c_int,
        arg7: *mut f64,
        arg8: *mut ::std::os::raw::c_int,
    );
    pub fn dgeco_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut f64,
        arg6: *mut f64,
    );
    pub fn dgedi_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut f64,
        arg6: *mut f64,
        arg7: *mut ::std::os::raw::c_int,
    );
    pub fn dgefa_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut ::std::os::raw::c_int,
    );
    pub fn dgesl_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut f64,
        arg6: *mut ::std::os::raw::c_int,
    );
    pub fn dgtsl_(
        arg1: *mut ::std::os::raw::c_int,
        arg2: *mut f64,
        arg3: *mut f64,
        arg4: *mut f64,
        arg5: *mut f64,
        arg6: *mut ::std::os::raw::c_int,
    );
    pub fn dpbco_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut f64,
        arg6: *mut f64,
        arg7: *mut ::std::os::raw::c_int,
    );
    pub fn dpbdi_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut f64,
    );
    pub fn dppco_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut f64,
        arg4: *mut f64,
        arg5: *mut ::std::os::raw::c_int,
    );
    pub fn dppdi_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut f64,
        arg4: *mut ::std::os::raw::c_int,
    );
    pub fn dppfa_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
    );
    pub fn dppsl_(arg1: *mut f64, arg2: *mut ::std::os::raw::c_int, arg3: *mut f64);
    pub fn dptsl_(arg1: *mut ::std::os::raw::c_int, arg2: *mut f64, arg3: *mut f64, arg4: *mut f64);
    pub fn dsico_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut f64,
        arg6: *mut f64,
    );
    pub fn dsidi_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut f64,
        arg6: *mut ::std::os::raw::c_int,
        arg7: *mut f64,
        arg8: *mut ::std::os::raw::c_int,
    );
    pub fn dsifa_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut ::std::os::raw::c_int,
    );
    pub fn dsisl_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
        arg5: *mut f64,
    );
    pub fn dspco_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut f64,
        arg5: *mut f64,
    );
    pub fn dspdi_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut f64,
        arg5: *mut ::std::os::raw::c_int,
        arg6: *mut f64,
        arg7: *mut ::std::os::raw::c_int,
    );
    pub fn dspfa_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ::std::os::raw::c_int,
    );
    pub fn dspsl_(
        arg1: *mut f64,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut f64,
    );
}
