name: Documents

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Docs
        run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options"

      - name: Setup Pages
        uses: actions/configure-pages@v3

      # As of v1.0.9, upload-pages-artifact action rejects files with incorrect permissions.
      # In Rust doc's case, .lock is such a file.
      #
      # cf. https://github.com/actions/deploy-pages/issues/188#issuecomment-1597651901
      - name: Remove unnecessary files
        run: rm -f ./target/doc/.lock

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './target/doc'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
